export const STUDENT_CAPABILITIES = [
  { key: 'academic_advisor_tracking', label: '学业导师跟踪', category: 'academic' },
  { key: 'course_warning_monitor', label: '课程预警监控', category: 'academic' },
  { key: 'graduation_credit_audit', label: '毕业学分审计', category: 'academic' },
  { key: 'exam_makeup_plan', label: '补考计划管理', category: 'academic' },
  { key: 'gpa_target_management', label: '绩点目标管理', category: 'academic' },
  { key: 'research_project_record', label: '科研项目记录', category: 'academic' },
  { key: 'competition_award_record', label: '竞赛获奖记录', category: 'academic' },
  { key: 'certificate_archive', label: '资格证书归档', category: 'academic' },
  { key: 'innovation_credit_recognition', label: '创新学分认定', category: 'academic' },
  { key: 'library_overdue_alert', label: '图书逾期提醒', category: 'academic' },
  { key: 'attendance_anomaly_alert', label: '考勤异常预警', category: 'behavior' },
  { key: 'discipline_case_tracking', label: '违纪案例跟踪', category: 'behavior' },
  { key: 'daily_behavior_score', label: '日常行为评分', category: 'behavior' },
  { key: 'dormitory_checkin_record', label: '宿舍查寝记录', category: 'behavior' },
  { key: 'leave_approval_history', label: '请假审批历史', category: 'behavior' },
  { key: 'volunteer_service_hours', label: '志愿服务时长', category: 'behavior' },
  { key: 'club_activity_participation', label: '社团活动参与', category: 'behavior' },
  { key: 'campus_event_checkin', label: '校园活动签到', category: 'behavior' },
  { key: 'reward_punishment_file', label: '奖惩档案管理', category: 'behavior' },
  { key: 'counselor_interview_log', label: '辅导员访谈日志', category: 'behavior' },
  { key: 'tuition_payment_status', label: '学费缴纳状态', category: 'support' },
  { key: 'scholarship_application', label: '奖学金申请进度', category: 'support' },
  { key: 'financial_aid_case', label: '助学金档案', category: 'support' },
  { key: 'employment_intention_survey', label: '就业意向调查', category: 'support' },
  { key: 'internship_agreement_record', label: '实习协议记录', category: 'support' },
  { key: 'psychological_risk_alert', label: '心理风险预警', category: 'support' },
  { key: 'health_report_archive', label: '健康体检档案', category: 'support' },
  { key: 'insurance_coverage_status', label: '保险参保状态', category: 'support' },
  { key: 'parent_contact_followup', label: '家校沟通跟进', category: 'support' },
  { key: 'graduation_destination_tracking', label: '毕业去向跟踪', category: 'support' }
] as const;

export type StudentCapabilityKey = (typeof STUDENT_CAPABILITIES)[number]['key'];
